#!/usr/bin/env python3
"""Trim wall logos to their content box and write their optical metrics.

The brand walls size each logo by visual weight instead of one shared
max-height, so a 12:1 wordmark, a square badge and an export with a wide
transparent margin all read at the same presence. scripts/build_logos.py runs
this as its last step; it is also safe to run on its own at any time:

1. Every wall PNG is cropped in place to its visible content plus a 1px
   margin. The crop is lossless (pixels are copied, not re-baked) and the
   script is idempotent: a file that is already tight is left untouched.
   It never changes pixel values.
2. src/logo-metrics.js is regenerated: {'dir/file': [w, h, ink]}, where w/h
   are the trimmed pixel size and ink is the mean opacity inside that box
   (how heavy the mark reads). SVGs are not cropped; they report their
   viewBox size and the ink listed in SVG_INK.

The page falls back to the old fixed max-height for any file missing from
the manifest, so a stale manifest degrades gracefully rather than breaking.
"""
import json
import os
import re

import numpy as np
from PIL import Image

DIRS = ['operators', 'partners', 'members']
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
LOGOS = os.path.join(ROOT, 'public', 'logos')
OUT = os.path.join(ROOT, 'src', 'logo-metrics.js')
ALPHA_MIN = 10   # 4% opacity: anything fainter is invisible at the wall's .85 opacity
NEUTRAL_INK = 0.28  # the median PNG ink, used for any SVG not listed below
# PIL cannot rasterise SVG, so these inks were measured once from a browser
# raster of each file (same mean-opacity definition). Add a line when an SVG
# joins the walls; an unlisted SVG simply gets NEUTRAL_INK.
SVG_INK = {
    'operators/Caesars.svg': 0.11,
    'operators/ballys.svg': 0.33,
    'operators/casumo.svg': 0.8,
    'operators/espn-bet.svg': 0.51,
    'operators/fanduel.svg': 0.29,
    'operators/prizepicks.svg': 0.42,
}


def content_box(alpha):
    """(x0, y0, x1, y1) of the visible content plus a 1px margin, or None."""
    ys, xs = np.where(alpha > ALPHA_MIN)
    if len(xs) == 0:
        return None
    H, W = alpha.shape
    return (max(int(xs.min()) - 1, 0), max(int(ys.min()) - 1, 0),
            min(int(xs.max()) + 2, W), min(int(ys.max()) + 2, H))


def trim_png(path):
    im = Image.open(path)
    im.load()
    rgba = im.convert('RGBA')
    alpha = np.asarray(rgba)[..., 3]
    box = content_box(alpha)
    if box is None:
        return None, False
    H, W = alpha.shape
    x0, y0, x1, y1 = box
    changed = (x0, y0, x1, y1) != (0, 0, W, H)
    if changed:
        im.crop((x0, y0, x1, y1)).save(path, optimize=True)
    box = alpha[y0:y1, x0:x1].astype(np.float64) / 255.0
    return [x1 - x0, y1 - y0, round(float(box.mean()), 3)], changed


def svg_size(path, key):
    src = open(path, encoding='utf-8', errors='ignore').read(4096)
    m = re.search(r'viewBox="\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)', src)
    if not m:
        m = re.search(r'width="([\d.]+)(?:px)?"[^>]*height="([\d.]+)(?:px)?"', src)
    if not m:
        return None
    return [round(float(m.group(1)), 1), round(float(m.group(2)), 1), SVG_INK.get(key, NEUTRAL_INK)]


def main():
    metrics, trimmed = {}, 0
    for d in DIRS:
        folder = os.path.join(LOGOS, d)
        for f in sorted(os.listdir(folder)):
            path = os.path.join(folder, f)
            if f.lower().endswith('.png'):
                m, changed = trim_png(path)
                trimmed += changed
            elif f.lower().endswith('.svg'):
                m = svg_size(path, f'{d}/{f}')
            else:
                continue
            if m:
                metrics[f'{d}/{f}'] = m
            else:
                print('note: no metrics for', f'{d}/{f}')
    body = ',\n'.join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in sorted(metrics.items()))
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('// generated by scripts/logo_metrics.py (run by scripts/build_logos.py) - do not edit by hand\n')
        fh.write('// [width, height, ink]: trimmed pixel size and mean opacity of each wall logo\n')
        fh.write('export const LOGO_METRICS = {\n' + body + ',\n}\n')
    print(f'metrics: {len(metrics)} logos, trimmed {trimmed} files -> {os.path.relpath(OUT, ROOT)}')


if __name__ == '__main__':
    main()
